#!/bin/bash
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

sudo yum update -y
sudo yum install zsh -y

# for amazon linux
sudo chsh -s /bin/zsh ec2-user

# clear out previous config files
rm ~/.profile
rm ~/.bash_profile
rm ~/.zprofile
rm ~/.zshrc

mv ~/.profile ~/.profile.bak

ln -s ~/.dot/profile.linux ~/.profile
ln -s ~/.dot/zprofile ~/.zprofile
ln -s ~/.dot/zshrc ~/.zshrc
ln -s ~/.dot/oh-my-zsh/ ~/.oh-my-zsh

ln -s ~/.dot/vim/ ~/.vim
ln -s ~/.dot/vimrc ~/.vimrc
ln -s ~/.dot/gvimrc ~/.gvimrc

ln -s ~/.dot/tmux.linux ~/.tmux.conf

ln -s ~/.dot/gitconfig ~/.gitconfig
ln -s ~/.dot/gitignore ~/.gitignore

ln -s ~/.dot/ipython_config.py ~/.ipython/profile_default/ipython_config.py
mkdir ~/.config/nvim
ln -s ~/.dot/init.lua ~/.config/nvim/init.lua
ln -s ~/.vim/autoload ~/.config/nvim/autoload

# pluginstall vim deps
nvim +'PlugInstall --sync' +qa

# set git user to ddl
git config --global user.email "ryuta.oshikiri@dominodatalab.com"
# git config --list
